import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Navigation from "@/components/Navigation";
import { SpeedInsights } from "@vercel/speed-insights/next"
import Footer from "@/components/Footer";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bogdan Stevanovic - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} antialiased`}>
        <Navigation />
        {children}
        <Footer />
        <ToastContainer position="top-right" theme="dark" />
        <SpeedInsights />
      </body>
    </html>
  );
}
